version: '3.2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh ./docker-start.sh
    environment:
      - NODE_ENV=dev
    volumes:
      - ./application:/home/app
    ports:
      - "3333:3333"
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - dbvolume:/var/lib/mysql
    networks:
     - default
    ports: 
    - "3306:3306"
networks:
  default:
    driver: bridge
volumes:
  dbvolume:
    driver: "local"
